# Generated by Django 4.0.3 on 2022-03-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_remove_question_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ip',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
